### ISSUE TITLE
IllegalStateExeption on Chat Message

### ISSUE THREAD

**Issue by cravend** [Bryan-Correll/ServerLog#3]
Hi! I'm having trouble setting up this Plugin. Every time anyone sends a chat message, the following error occurs:
```
[15:06:52 ERROR]: Could not pass event AsyncPlayerChatEvent to ServerLog v1.1.2
java.lang.IllegalStateException: ServerLogEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:547) ~[patched_1.15.2.jar:git-Paper-143]
        at com.bryan.log.type.AsyncPlayerChatEvents.onChat(AsyncPlayerChatEvents.java:26) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor131.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-143]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-143]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-143]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1738) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1653) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.2.jar:git-Paper-143]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

I'm running a Waterfall (Bungee) server with Paper (Spigot) 1.15.2.

**Comment by cravend** [comment]
```
[15:15:07 ERROR]: Could not pass event AsyncPlayerChatEvent to ServerLog v1.1.2
java.lang.IllegalStateException: ServerLogEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[patched_1.15.2.jar:git-Paper-146]
        at com.bryan.log.type.AsyncPlayerChatEvents.onChat(AsyncPlayerChatEvents.java:26) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor131.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-146]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-146]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-146]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-146]
        at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1738) ~[patched_1.15.2.jar:git-Paper-146]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1653) ~[patched_1.15.2.jar:git-Paper-146]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.2.jar:git-Paper-146]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
Updated to the latest version of Paper, that didn't affect it.

**Comment by ProPhaze** [comment]
Thank you for making me aware of this issue. It was being caused by the event call being asynchronous as Spigot required it to be called from the main thread.

You can download the new working version [here](https://www.spigotmc.org/resources/server-log.65510/update?update=324646) or by compiling the source code from the GitHub.
